name: Docker Image CI

on:
  push:
    branches: [ testing ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag genygo/corekeeper:$(date +%s)
